### ISSUE TITLE
Support for tox-envreport 

### ISSUE THREAD

**Issue by saifsayyad** [useblocks/sphinx-test-reports#1]
### **test-env**
There shall be one new directive: test-env

`.. test-env:: env_1/env-report.json  # file name`
or
`.. test-env:: py27  # env name`

### **test-env-files**
One new configuration option must be added: test-env-files

`test-env-files = ["../.tox/tox-report.json"]`

If a file name is given for "test-env", the complete file shall be used as input data.
If an env-name is given, the name shall be searched inside given files by "test-env-files" and only found data shall be used as input data.

If file name or env name do not exist, an error note shall be printed at the current place of the directive.

### **test-env-data**
Another option "test-env-data" must be added, which stores the parametes, which shall be used for output:

`test-env-data = ["name", "host", "installed_packages"]`

Supported parameters are:

- name
- host
- installed_packages
- path
- plattform
- python
- reportversion
- setup
- test
- toxversion

### **:test-env:**
This configuration can be overwritten by each "test-env" directive by using the option "data":

```
.. test-env: my_env
   :data: name, host, test
```
 "data" is a comma separated list, which support "," and ";" as delimiter.

If a given parameter is not available, a warning shall be printed on command line.

### **:raw:**
If :raw: is given as option for test-env, the shall be only a single code-block, which contains the complete env data.

##  **Output**
The data shall be printed as follows:
Each :test-env: output is framed by a container with class=test-env

Each parameter shall be printed inside a "parameter" container which class=test-env-parameter and class=param_PARAM_NAME (e.g. param_host)

Each string/number parameter shall be printed by using sphinx field-names

`:param_name: param_value`

 dics/lists shall be printed inside a code-block without any special style.
The param_name shall be printed above the code-block (in bold).

**Comment by saifsayyad** [comment]
@danwos

**Comment by danwos** [comment]
We do not need ```test-env-files```.
This should be always given as first argument like  ```.. test-env:: FILE_PATH```.

In this case, we also need a new option ```:env:```, which defines the needed environment from imported env-file.

Example::

```
... test-env:: my_tox_file.json
   :env: PYTHON27, PYTHON36
   :data: name, host, version
```
