### ISSUE TITLE
Custom template for the test report directive

### ISSUE THREAD

**Issue by jakehader** [useblocks/sphinx-test-reports#13]
It does not appear that adding a custom test_report template is supported in the `TestReportDirective` class:

https://github.com/useblocks/sphinx-test-reports/blob/20e1828a01b9085ec36e088d79cdd0b3c4f37efa/sphinxcontrib/test_reports/directives/test_report.py#L37-L38

It would be nice if this could be pulled out as a configurable setting.

**Comment by danwos** [comment]
Agree, that would be really helpful.

I suggest a config var ``tr_report_template``, which needs a relative path from ``conf.py`` location.
Then this is used as template.

But I think some additional docs are needed to describe the usage of templates and the available vars in it.

**Comment by jakehader** [comment]
Thanks for the reply! I forked the repo and was trying to play around with adding something to `conf.py` but didn't know where to start. I was trying to use the `sphinx-needs` project as a example but didn't get very far.

I would be happy to help and submit a PR if you could link some documentation on how you'd like it done. It might be faster for you to implement though given my limited knowledge of the project right now.

**Comment by elupus** [comment]
Seems this is resolved?
