### ISSUE TITLE
Released version is incompatible with Sphinx 4

### ISSUE THREAD

**Issue by hkaimio** [useblocks/sphinx-test-reports#14]
Now that Sphinx 4 has been released, sphinx-test-report is no longer compatible with it because it uses the add_stylesheet method of Sphinx application object instead of the current add_css_file method.

This has apparently been fixed in sphinx-test-reports 0.3.4 but that version is not yet available in PyPi. This break default installation with and prevents us from upgrading to Sphinx 4.0.

**Comment by twodrops** [comment]
I can get it installed from PyPi with
`pip install sphinx-test-reports==0.3.4`

`pip install sphinx-test-reports` defaults to 0.3.3. 

@danwos  Any idea why?

**Comment by twodrops** [comment]
I now see that 0.3.4 is yanked.
https://pypi.org/project/sphinx-test-reports/#history

Is this something you can change @danwos ?

**Comment by danwos** [comment]
Yeah I yanked the 0.3.4 release because of an unresolved major bug I found after the release. :/
But I uploaded 0.3.5 now, which works also with sphinx >= 4.0
