### ISSUE TITLE
Add support for sphinx parallel modes

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-test-reports#20]
Add support for sphinx parallel read and write

**Comment by twodrops** [comment]
@danwos Is this part of 0.3.5 already? I tested 0.3.5 now but it still throws the warning. If I install it locally from sources (with my original changes), it works fine. Can you please double-check if 0.3.5 includes the changes for parallel-build?

**Comment by danwos** [comment]
Argh sh**, 0.3.5 got already released a couple of months ago. The changelog is wrong and this feature will be released with 0.3.6.
So you need the code from master to test it.

Will fix and release it this week.

**Comment by danwos** [comment]
Released 0.3.6 on pypi https://pypi.org/project/sphinx-test-reports/, which includes this changes
