### ISSUE TITLE
Not able to find information related to generic 'test' directive

### ISSUE THREAD

**Issue by AyoubSabri** [useblocks/sphinx-test-reports#26]
Hello,

I am looking for a way to generate a sphinx test-plan from docstrings included in my pytest test-suite. 
I came across this [stackoverflow question](https://stackoverflow.com/questions/54807126/python-dynamic-test-plan-generation), where _danwos_ answer suggests an approach based on the **sphinx-test-reports** plugin.

I tried to use the `test-case` directive but I got following error: 

```
File "/local/home/sabria/.local/lib/python3.8/site-packages/sphinxcontrib/test_reports/directives/test_common.py", line 98, in prepare_basic_options
    self.test_file_given = self.test_file[:]
TypeError: 'NoneType' object is not subscriptable
```

It looks like junit xml test reports are mandatory to generate documentation when using this directive (i didn't provide the `file` option).
I didn't encounter this problem when I tried the `test` directive (presented in danwos's answer).

```
def my_test():
    """
    .. test:: My test case
       :id: TEST_001
       :status: in progress
       :author: me

       This test case checks for **awesome** stuff.
    """
    a = 2
    b = 5
    # ToDo: chek if a+b = 7
```

The issue is that I was not able to find in the project's documentation information about this one. I would like to have something that not depends on the junit xml file.
Is the `test` directive still supported by your plugin? Where can I find examples?

Thank you

**Comment by danwos** [comment]
Hi, 
Sphinx-Test-Reports needs a junit xml file, as this is the source of test results and test status.

If you just want to document your test-cases, you can use Sphinx [autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html), which documents every kind of Python code.

Simply add our test-folder to the Path (`sys.path.append("...") in your conf.py`) and use it inside your rst file:
```rst
My tests
========

.. automodule:: test.my_tests:
   :members:
```

Sphinx-Test-Report is needed for the later step, when you want to link the test results to the documented test cases.

Was this answer helpful? I'm not 100% sure if I have understood your problem the right way.

**Comment by AyoubSabri** [comment]
Thank you for your quick answer.

You're right I could use Sphinx autodoc for my needs, but I prefer the output generated when using the `test` directive which seems to come from your plugin. My issue is that I can found documentation about so that I can see which options are available.

Here is the output with autodoc:

<img width="183" alt="autodoc" src="https://user-images.githubusercontent.com/34887622/143591407-159b6723-88b2-4894-a2cd-ffa7bea9cb13.PNG">

And here is the output when using autodoc and the `test` directive included in your plugin:

<img width="298" alt="test_report_plugin" src="https://user-images.githubusercontent.com/34887622/143591403-0b5acc35-bd7b-4de9-88fd-9e928272ac92.PNG">

Thank you in advance.

P.S: I will have a closer look at the way it is possible to link test-cases and test-results

**Comment by AyoubSabri** [comment]
Finally I realized that the test _directive_ I was looking for is a need type and comes from [sphinx-needs](https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/need.html) plugin.

**Comment by danwos** [comment]
Yes that's right.
Just  use ``.. test::`` inside the docstring of a test case and then ``automodule`` to get the above output. 
Sorry for not being detailed enough.
