### ISSUE TITLE
Incompatibility with latest robot framework (5.0) changes

### ISSUE THREAD

**Issue by nicobucher** [useblocks/sphinx-test-reports#30]
Previously, xUnit reports generated by robot framework were handled correctly by sphinx-test-reports.

With the latest version Robot Framework 5.0, however, there was a change in the layout of the XML report file.
See discussion here: https://github.com/robotframework/robotframework/issues/2982

The reports now contain nested <testsuite> elements like this:
```
<testsuite>
   <testsuite>
      <testcase>
and so on
```

When importing such a report with test-file/test-report directive, I get the error message:
`AttributeError: no such child: testcase`

It would be great if sphinx-test-reports would support nested testsuites to continue compatibility with robot framework.

**Comment by mawieland** [comment]
Hi, can you post a (redacted if needed) xml output from your robot framework? I've done tests with my own nested xml file but would like to test on a non artificial input. Thanks!

**Comment by danwos** [comment]
Closed by #31
