### ISSUE TITLE
Support for Google test XML Report

### ISSUE THREAD

**Issue by petermla** [useblocks/sphinx-test-reports#7]
I have tested testsphinx-test-reports with Google test XML Report and I get some errors.
As  far as i can tell, google uses more XML tags as your test sample xml_data_2.xml (one <testsuites> and multiple <testsuite> with <testcase>).  I have deleted the extra tags and have produced a Sphinx output. 

Is the Google test XML Report something that will be supported in future or am i doing something wrong?

Example:
`<?xml version="1.0" encoding="UTF-8"?>`
`<testsuites tests="40" failures="0" disabled="0" errors="0" timestamp="2019-01-07T14:21:56" time="0.047" name="AllTests">`
  `<testsuite name="testsuite1" tests="1" failures="0" disabled="0" errors="0" time="0">`
    `<testcase name="testsuite1case1" status="run" time="0" classname="testsuite1" />`
  `</testsuite>`
  `<testsuite name="testsuite2" tests="8" failures="0" disabled="0" errors="0" time="0">`
    `<testcase name="testsuite2case1" status="run" time="0" classname="testsuite2" />`
    `<testcase name="testsuite2case2" status="run" time="0" classname="testsuite2" />`
    `<testcase name="testsuite2case3" status="run" time="0" classname="testsuite2" />`
  `</testsuite>`
`</testsuites>`

**Comment by danwos** [comment]
Thanks for your feedback regarding the Google test XML Report.
Do be honest I haven't used the Google Test till now and would need some time to dive deeper and understand their output format.
But it is absolutely planned to support different "dialects" of junit xml output format.

So if you have any further information or some specification about the used format by google test, this would be really helpful.
Or you may be able to upload a xml-file generated with google test.

**Comment by danwos** [comment]
Should be fixed with #9.
As I'm not using Google test, I'm unable to test it.
