### ISSUE TITLE
pytest 5.1.0 outputs incompatible junit.xml

### ISSUE THREAD

**Issue by ptillemans** [useblocks/sphinx-test-reports#8]
In pytest-5.1.0 bugfix https://github.com/pytest-dev/pytest/issues/5477  was included which adds a *testsuites* root element.

see also https://github.com/useblocks/sphinx-test-reports/issues/7

This breaks test reports in sphinx.

**Comment by danwos** [comment]
Thanks for the bug report and especially for the pull request.
Merged it and uploaded a new version 0.2.1.

Added you also to the AUTHORS file. I hope that's okay for you.

And thanks again for your help!
